### ISSUE TITLE
product photo's not show fix it  and  set another photo

### ISSUE THREAD

**Issue by Raj2342** [Raj2342/ROMAN-REING#1]
![image](https://github.com/Raj2342/ROMAN-REING/assets/120565750/cd472367-6e56-40ed-a5a3-ac1a3335dda5)
destination -  our products < view all  and scroll down 
 desire output:  set any potato photo as you wish

**Comment by AnukratiMehta** [comment]
@Raj2342 I've added all the images. Please merge the branch. Thanks!

**Comment by Raj2342** [comment]
@AnukratiMehta  thanks  i have merged  branch
